### ISSUE TITLE
Use mocha-clean with gulp-mocha

### ISSUE THREAD

**Issue by boxfoot** [rstacruz/mocha-clean#2]
Are there any instructions for how to use mocha-clean with gulp-mocha?

I tried to do this, but it didn't work:

```javascript
var gulp = require('gulp'),
  plugins = require('gulp-load-plugins')();

gulp.task('runSpecificTestSuite', function () {
    require('mocha-clean');
    return gulp.src('path/to//spec', {read: false})
        .pipe(plugins.mocha());
});
```

This runs the tests as expected, but uses the full stack-traces.  It looks to me like gulp-mocha is loading mocha from it's own `node_modules` folder, so the monkey-patching that happens when I first `require('mocha-clean')` is ignored...

**Comment by rstacruz** [comment]
Updated: https://github.com/rstacruz/mocha-clean/blob/master/docs/Using_with_mocha_loaders.md

Thanks everyone.

**Comment by baha-nur** [comment]
I wasn't sure where to ask, this threaded seemed most relevant.

I can't get mocha-clean to work with gulp-spawn-mocha. 
I've included `--require mocha-clean` in mocha.opts and running `node_modules/.bin/mocha test/index.js test/integration/User.api.spec.js` works as expected.

Here's my stripped down gulpfile that should be mimicking the above, but somehow fails to load mocha.opts:

```
const gulp  = require("gulp"),
    env     = require("gulp-env"),
    mocha   = require('gulp-spawn-mocha'),

gulp.task("mocha", () => {
    return gulp.src(["test/index.js", "test/integration/User.api.spec.js"]), { read: false })
        .pipe(mocha({ // }))
});
```

Any ideas what I'm missing here?
