### ISSUE TITLE
mocha-clean is unnecessary? 

### ISSUE THREAD

**Issue by hellboy81** [rstacruz/mocha-clean#8]
Have installed `mocha-clean`. Got message:

```sh
npm WARN deprecated mocha-clean@0.4.0: Mocha 2.2.5 already shortens stack traces by default.
```

How can I enable stack trace shortener in mocha by default?

**Comment by rstacruz** [comment]
Shouldn't it already be on?

https://github.com/visionmedia/mocha/issues/545

**Comment by djanowski** [comment]
Looks like it's there but they want to remove it? See https://github.com/mochajs/mocha/issues/1950

**Comment by rstacruz** [comment]
gotcha... probably time to remove that notice

**Comment by rstacruz** [comment]
Removed it. Also updated the readme c9fe938df582fdb7a66cea463e6d9ef8c118b341. Cheers!
